name: Check for major dependency updates

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    name: Check for major dependency updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          persist-credentials: false

      - name: Extract Go version
        uses: arnested/go-version-action@077589a96e5aeea271983eb6f18465c54ea7f540 # v1.1.20
        id: go-version

      - name: Set up Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ steps.go-version.outputs.go-mod-version }}
          check-latest: true

      - name: Install `gomajor`
        run: go install github.com/icholy/gomajor@4439c423d4f92ed1214c2a51750b6c34c4c70aa6 # v0.14.0

      - name: Run `gomajor`
        id: gomajor
        run: |
          {
            echo 'major_dependencies<<EOF'
            gomajor list -major | awk '{print "> "$0}'
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - name: Comment PR to update major dependencies
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        with:
          comment-tag: major_dependencies
          mode: ${{ steps.gomajor.outputs.major_dependencies != '' && 'upsert' || 'delete' }}
          message: |
            > [!IMPORTANT]
            > ## :warning: Major dependencies need updated :warning:
            >
            > The following major dependencies are outdated:
            > ```
            ${{ steps.gomajor.outputs.major_dependencies }}
            > ```
